apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    role: frontend

spec:
  selector:
    matchLabels:
      pod: frontend

  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      name: {{ .Values.name }}-pod
      labels:
        pod: frontend

    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.img }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        stdin: true
        tty: true
        resources:
          limits:
            cpu: "200m"
          requests:
            cpu: "100m"
      #imagePullSecrets:
      #- name: regcred
