name: Build new Docker img
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Nginx-Build 
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Img
      run: |
        echo "${{ secrets.my_docker_login}}" | docker login -u "alirom93" --password-stdin
        docker-compose build
        docker-compose push
      
